services:
  web:
    build: .
    ports:
      - "7001:7001"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/camera_alerts
      - REDIS_URL=redis://redis:6379/0
      - PORT=7001

  worker:
    build: .
    command: rq worker camera_tasks
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/camera_alerts
      - REDIS_URL=redis://redis:6379/0
      - PORT=7001

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:7001

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=camera_alerts
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data:
